<a href="https://colab.research.google.com/github/Tymo-8/hello-world/blob/main/Numpy_lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [3]:
x=np.array([1,2,3,4,5,6])

# **Właściwości tablic 'np.array'**

In [4]:
x.argmax()

5

In [5]:
x.dtype

dtype('int64')

In [6]:
x.shape

(6,)

In [7]:
x = x.reshape(2,3)

In [8]:
x.ndim

2

In [9]:
x.shape

(2, 3)

In [10]:
x = np.array([[1.2,3,4.,3.2],[1.3,4.5,6.2,3]],dtype='float')

In [11]:
x.dtype

dtype('float64')

# **Tworzenie tablic**

In [12]:
x= np.zeros(shape=(2,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [13]:
y=np.ones(shape=(2,4,3), dtype='int')
y

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [14]:
x = np.arange(10,1, -0.05)
x

array([10.  ,  9.95,  9.9 ,  9.85,  9.8 ,  9.75,  9.7 ,  9.65,  9.6 ,
        9.55,  9.5 ,  9.45,  9.4 ,  9.35,  9.3 ,  9.25,  9.2 ,  9.15,
        9.1 ,  9.05,  9.  ,  8.95,  8.9 ,  8.85,  8.8 ,  8.75,  8.7 ,
        8.65,  8.6 ,  8.55,  8.5 ,  8.45,  8.4 ,  8.35,  8.3 ,  8.25,
        8.2 ,  8.15,  8.1 ,  8.05,  8.  ,  7.95,  7.9 ,  7.85,  7.8 ,
        7.75,  7.7 ,  7.65,  7.6 ,  7.55,  7.5 ,  7.45,  7.4 ,  7.35,
        7.3 ,  7.25,  7.2 ,  7.15,  7.1 ,  7.05,  7.  ,  6.95,  6.9 ,
        6.85,  6.8 ,  6.75,  6.7 ,  6.65,  6.6 ,  6.55,  6.5 ,  6.45,
        6.4 ,  6.35,  6.3 ,  6.25,  6.2 ,  6.15,  6.1 ,  6.05,  6.  ,
        5.95,  5.9 ,  5.85,  5.8 ,  5.75,  5.7 ,  5.65,  5.6 ,  5.55,
        5.5 ,  5.45,  5.4 ,  5.35,  5.3 ,  5.25,  5.2 ,  5.15,  5.1 ,
        5.05,  5.  ,  4.95,  4.9 ,  4.85,  4.8 ,  4.75,  4.7 ,  4.65,
        4.6 ,  4.55,  4.5 ,  4.45,  4.4 ,  4.35,  4.3 ,  4.25,  4.2 ,
        4.15,  4.1 ,  4.05,  4.  ,  3.95,  3.9 ,  3.85,  3.8 ,  3.75,
        3.7 ,  3.65,

In [15]:
x = np.linspace(start=10, stop=1, num=10)
x

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

**Zmiana rozmiaru tablicy**
---
wartosc '-1' oznacza, że Python ma domyślnie dobrać drugi rozmiar tablicy

In [16]:
x.reshape((-1,2))

array([[10.,  9.],
       [ 8.,  7.],
       [ 6.,  5.],
       [ 4.,  3.],
       [ 2.,  1.]])

**Generowanie liczb pseudolosowych**

In [17]:
np.random.seed(0)

In [18]:
np.random.randn(4,5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [19]:
np.random.rand(4,5)

array([[0.14335329, 0.94466892, 0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547, 0.66676672, 0.67063787]])

In [20]:
np.random.randint(low=10, high=80,size=(4,5))

array([[56, 10, 24, 63, 22],
       [52, 78, 16, 78, 57],
       [13, 62, 25, 30, 68],
       [33, 23, 58, 59, 79]])

In [21]:
x=np.arange(4,5,.05)
np.random.choice(x)

4.449999999999998

In [22]:
x

array([4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ,
       4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95])

In [23]:
x.shape

(20,)

In [24]:
np.random.shuffle(x)
x

array([4.65, 4.3 , 4.5 , 4.45, 4.4 , 4.75, 4.85, 4.35, 4.55, 4.6 , 4.95,
       4.8 , 4.7 , 4.2 , 4.1 , 4.05, 4.9 , 4.25, 4.  , 4.15])

# **Podstawowe funkcje**

In [25]:
np.exp(1)

2.718281828459045

In [26]:
np.sqrt(20)

4.47213595499958

In [27]:
np.all([0,1,3,4,5])

False

In [28]:
np.any([1,2,3,4,5,6])

True

In [29]:
bool(0.2)

True

In [30]:
A=np.random.rand(10)
A

array([0.12019656, 0.2961402 , 0.11872772, 0.31798318, 0.41426299,
       0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805])

In [31]:
np.argmax(A)

6

In [32]:
np.argsort(A)

array([5, 2, 0, 8, 1, 3, 4, 9, 7, 6])

In [33]:
np.median(A)

0.3070616884580605

In [34]:
np.max(A)

0.6924721193700198

## **Indeksowanie i wycinanie danych**

In [35]:
A

array([0.12019656, 0.2961402 , 0.11872772, 0.31798318, 0.41426299,
       0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805])

In [36]:
A[2:]

array([0.11872772, 0.31798318, 0.41426299, 0.0641475 , 0.69247212,
       0.56660145, 0.26538949, 0.52324805])

In [37]:
A[-2:]

array([0.26538949, 0.52324805])

In [38]:
B = A[-2:]
A

array([0.12019656, 0.2961402 , 0.11872772, 0.31798318, 0.41426299,
       0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805])

In [39]:
B

array([0.26538949, 0.52324805])

In [40]:
A = np.random.randint(low=1, high=100, size=(4,5))
A

array([[42, 59, 66, 37, 11],
       [87, 44, 12,  3, 52],
       [81, 33, 55,  1, 39],
       [20, 47, 43, 57, 61]])

In [41]:
A[1:3,-2:]

array([[ 3, 52],
       [ 1, 39]])

**Iteracja po tablicy**

In [46]:
A = np.random.randint(low=1, high=100, size=(4,6))
A

array([[ 5, 68, 12, 87, 78, 76],
       [57, 17, 25, 30, 22, 26],
       [81, 61, 62, 84, 34, 33],
       [71, 86, 32, 14, 72, 57]])

In [47]:
np.ravel(A)

array([ 5, 68, 12, 87, 78, 76, 57, 17, 25, 30, 22, 26, 81, 61, 62, 84, 34,
       33, 71, 86, 32, 14, 72, 57])

In [48]:
A.T

array([[ 5, 57, 81, 71],
       [68, 17, 61, 86],
       [12, 25, 62, 32],
       [87, 30, 84, 14],
       [78, 22, 34, 72],
       [76, 26, 33, 57]])

In [50]:
A>50

array([[False,  True, False,  True,  True,  True],
       [ True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False],
       [ True,  True, False, False,  True,  True]])

In [51]:
A[A>50]

array([68, 87, 78, 76, 57, 81, 61, 62, 84, 71, 86, 72, 57])

In [52]:
A

array([[ 5, 68, 12, 87, 78, 76],
       [57, 17, 25, 30, 22, 26],
       [81, 61, 62, 84, 34, 33],
       [71, 86, 32, 14, 72, 57]])

In [54]:
np.bitwise_and(A>60, A<80)

array([[False,  True, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [ True, False, False, False,  True, False]])

In [55]:
A[np.bitwise_and(A>60, A<80)]

array([68, 78, 76, 61, 62, 71, 72])